include:
  - board: nice_nano_v2
    shield: choco_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: choco_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
